/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "C:\\Users\\86189\\Desktop\\Temp\\npm\\create-ui\\node_modules\\.pnpm\\@vuepress+core@1.9.7\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "C:\\Users\\86189\\Desktop\\Temp\\npm\\create-ui\\node_modules\\.pnpm\\@vuepress+plugin-active-header-links@1.9.7\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "C:\\Users\\86189\\Desktop\\Temp\\npm\\create-ui\\node_modules\\.pnpm\\@vuepress+plugin-nprogress@1.9.7\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2
]