/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\86189\\Desktop\\Temp\\npm\\create-ui\\node_modules\\.pnpm\\@vuepress+core@1.9.7\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-c2f985d2",
    path: "/components/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c2f985d2").then(next)
    },
  },
  {
    path: "/components/index.html",
    redirect: "/components/"
  },
  {
    name: "v-795b6ff4",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-795b6ff4").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-046fcccc",
    path: "/components/chatbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-046fcccc").then(next)
    },
  },
  {
    name: "v-269cebd8",
    path: "/components/modal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-269cebd8").then(next)
    },
  },
  {
    name: "v-7a31fd8c",
    path: "/components/loading.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a31fd8c").then(next)
    },
  },
  {
    name: "v-a8d46338",
    path: "/components/toast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8d46338").then(next)
    },
  },
  {
    name: "v-42d3ebba",
    path: "/en/components/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42d3ebba").then(next)
    },
  },
  {
    path: "/en/components/index.html",
    redirect: "/en/components/"
  },
  {
    name: "v-6da8d8b4",
    path: "/components/musicbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6da8d8b4").then(next)
    },
  },
  {
    name: "v-3530a5c7",
    path: "/en/components/chatbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3530a5c7").then(next)
    },
  },
  {
    name: "v-3a5b6792",
    path: "/en/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a5b6792").then(next)
    },
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-79ba92fe",
    path: "/en/components/musicbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79ba92fe").then(next)
    },
  },
  {
    name: "v-5f8e55a7",
    path: "/en/components/loading.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f8e55a7").then(next)
    },
  },
  {
    name: "v-334788f2",
    path: "/en/components/modal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-334788f2").then(next)
    },
  },
  {
    name: "v-a93e8672",
    path: "/en/components/toast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a93e8672").then(next)
    },
  },
  {
    name: "v-4ca31fec",
    path: "/en/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ca31fec").then(next)
    },
  },
  {
    path: "/en/guide/index.html",
    redirect: "/en/guide/"
  },
  {
    name: "v-3d6af587",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d6af587").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]