/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "CreateUI",
  "description": "",
  "base": "/CreateUI/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/CreateUI/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "开始使用 !",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "个性化",
            "details": "充满创造性和个性组件库。"
          },
          {
            "title": "Vue驱动",
            "details": "Vue2基础上完成，可全局或按需引入。"
          },
          {
            "title": "轻量",
            "details": "通过配置webpack打包，体积小巧。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-795b6ff4",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/components/",
      "relativePath": "components/README.md",
      "key": "v-c2f985d2",
      "path": "/components/",
      "headers": [
        {
          "level": 2,
          "title": "组件列表",
          "slug": "组件列表"
        }
      ]
    },
    {
      "title": "畅聊气泡",
      "frontmatter": {
        "tags": [
          "聊天",
          "chat",
          "bubble"
        ]
      },
      "regularPath": "/components/chatbox.html",
      "relativePath": "components/chatbox.md",
      "key": "v-046fcccc",
      "path": "/components/chatbox.html",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "高级用法",
          "slug": "高级用法"
        },
        {
          "level": 3,
          "title": "昵称",
          "slug": "昵称"
        },
        {
          "level": 3,
          "title": "头像",
          "slug": "头像"
        },
        {
          "level": 3,
          "title": "时间戳",
          "slug": "时间戳"
        },
        {
          "level": 3,
          "title": "背景颜色",
          "slug": "背景颜色"
        },
        {
          "level": 3,
          "title": "连续消息",
          "slug": "连续消息"
        },
        {
          "level": 3,
          "title": "气泡宽度",
          "slug": "气泡宽度"
        },
        {
          "level": 2,
          "title": "配置项",
          "slug": "配置项"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        }
      ]
    },
    {
      "title": "加载动画",
      "frontmatter": {
        "tags": [
          "加载",
          "load"
        ]
      },
      "regularPath": "/components/loading.html",
      "relativePath": "components/loading.md",
      "key": "v-7a31fd8c",
      "path": "/components/loading.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        },
        {
          "level": 2,
          "title": "高级用法",
          "slug": "高级用法"
        },
        {
          "level": 3,
          "title": "全屏加载",
          "slug": "全屏加载"
        },
        {
          "level": 3,
          "title": "配置选项",
          "slug": "配置选项"
        },
        {
          "level": 3,
          "title": "加载控制",
          "slug": "加载控制"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        },
        {
          "level": 3,
          "title": "函数",
          "slug": "函数"
        }
      ]
    },
    {
      "title": "八音盒",
      "frontmatter": {
        "tags": [
          "音乐",
          "音乐盒",
          "music",
          "musicbox"
        ]
      },
      "regularPath": "/components/musicbox.html",
      "relativePath": "components/musicbox.md",
      "key": "v-6da8d8b4",
      "path": "/components/musicbox.html",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "高级用法",
          "slug": "高级用法"
        },
        {
          "level": 3,
          "title": "主体颜色",
          "slug": "主体颜色"
        },
        {
          "level": 3,
          "title": "背景颜色",
          "slug": "背景颜色"
        },
        {
          "level": 3,
          "title": "进度条长度",
          "slug": "进度条长度"
        },
        {
          "level": 3,
          "title": "Ref 引用",
          "slug": "ref-引用"
        },
        {
          "level": 3,
          "title": "Audio 上下文",
          "slug": "audio-上下文"
        },
        {
          "level": 3,
          "title": "Audio 分析器",
          "slug": "audio-分析器"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        },
        {
          "level": 3,
          "title": "事件",
          "slug": "事件"
        },
        {
          "level": 3,
          "title": "Ref",
          "slug": "ref"
        }
      ]
    },
    {
      "title": "模态对话框",
      "frontmatter": {
        "tags": [
          "弹框",
          "提示框",
          "dialog"
        ]
      },
      "regularPath": "/components/modal.html",
      "relativePath": "components/modal.md",
      "key": "v-269cebd8",
      "path": "/components/modal.html",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "高级用法",
          "slug": "高级用法"
        },
        {
          "level": 3,
          "title": "对齐方式",
          "slug": "对齐方式"
        },
        {
          "level": 3,
          "title": "回调函数",
          "slug": "回调函数"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "Start !",
        "actionLink": "/en/guide/",
        "features": [
          {
            "title": "Personality",
            "details": "This is a personality and creative lib."
          },
          {
            "title": "Vue Driven",
            "details": "Based on Vue2 and support import by Global or Demand."
          },
          {
            "title": "Small",
            "details": "Configure by webpack, it has small volume."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/en/",
      "relativePath": "en/README.md",
      "key": "v-3a5b6792",
      "path": "/en/"
    },
    {
      "title": "Intro",
      "frontmatter": {},
      "regularPath": "/en/components/",
      "relativePath": "en/components/README.md",
      "key": "v-42d3ebba",
      "path": "/en/components/",
      "headers": [
        {
          "level": 2,
          "title": "Components",
          "slug": "components"
        }
      ]
    },
    {
      "title": "Chatting Bubble",
      "frontmatter": {
        "tags": [
          "聊天",
          "chat",
          "bubble"
        ]
      },
      "regularPath": "/en/components/chatbox.html",
      "relativePath": "en/components/chatbox.md",
      "key": "v-3530a5c7",
      "path": "/en/components/chatbox.html",
      "headers": [
        {
          "level": 2,
          "title": "Basic Usage",
          "slug": "basic-usage"
        },
        {
          "level": 2,
          "title": "Adanced Usage",
          "slug": "adanced-usage"
        },
        {
          "level": 3,
          "title": "Nickname",
          "slug": "nickname"
        },
        {
          "level": 3,
          "title": "Avatar",
          "slug": "avatar"
        },
        {
          "level": 3,
          "title": "TimeStamp",
          "slug": "timestamp"
        },
        {
          "level": 3,
          "title": "Background Color",
          "slug": "background-color"
        },
        {
          "level": 3,
          "title": "Successive Msgs",
          "slug": "successive-msgs"
        },
        {
          "level": 3,
          "title": "Bubble width",
          "slug": "bubble-width"
        },
        {
          "level": 2,
          "title": "Configure",
          "slug": "configure"
        },
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "消息提示框",
      "frontmatter": {
        "tags": [
          "通知",
          "提醒",
          "message",
          "remind"
        ]
      },
      "regularPath": "/components/toast.html",
      "relativePath": "components/toast.md",
      "key": "v-a8d46338",
      "path": "/components/toast.html",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "高级用法",
          "slug": "高级用法"
        },
        {
          "level": 3,
          "title": "提示类型",
          "slug": "提示类型"
        },
        {
          "level": 3,
          "title": "延迟时间",
          "slug": "延迟时间"
        },
        {
          "level": 3,
          "title": "顶部偏移",
          "slug": "顶部偏移"
        },
        {
          "level": 3,
          "title": "回调函数（待完成）",
          "slug": "回调函数-待完成"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/components/loading.html",
      "relativePath": "en/components/loading.md",
      "key": "v-5f8e55a7",
      "path": "/en/components/loading.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/components/toast.html",
      "relativePath": "en/components/toast.md",
      "key": "v-a93e8672",
      "path": "/en/components/toast.html"
    },
    {
      "title": "八音盒",
      "frontmatter": {
        "tags": [
          "音乐",
          "音乐盒",
          "music",
          "musicbox"
        ]
      },
      "regularPath": "/en/components/musicbox.html",
      "relativePath": "en/components/musicbox.md",
      "key": "v-79ba92fe",
      "path": "/en/components/musicbox.html",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "高级用法",
          "slug": "高级用法"
        },
        {
          "level": 3,
          "title": "主体颜色",
          "slug": "主体颜色"
        },
        {
          "level": 3,
          "title": "背景颜色",
          "slug": "背景颜色"
        },
        {
          "level": 3,
          "title": "进度条长度",
          "slug": "进度条长度"
        },
        {
          "level": 3,
          "title": "Ref 引用",
          "slug": "ref-引用"
        },
        {
          "level": 3,
          "title": "Audio 上下文",
          "slug": "audio-上下文"
        },
        {
          "level": 3,
          "title": "Audio 分析器",
          "slug": "audio-分析器"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        },
        {
          "level": 3,
          "title": "事件",
          "slug": "事件"
        },
        {
          "level": 3,
          "title": "Ref",
          "slug": "ref"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/components/modal.html",
      "relativePath": "en/components/modal.md",
      "key": "v-334788f2",
      "path": "/en/components/modal.html"
    },
    {
      "title": "指南",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-3d6af587",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "功能",
          "slug": "功能"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "用法",
          "slug": "用法"
        },
        {
          "level": 3,
          "title": "全局引入",
          "slug": "全局引入"
        },
        {
          "level": 3,
          "title": "按需引入",
          "slug": "按需引入"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        }
      ]
    },
    {
      "title": "Guide",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/en/guide/",
      "relativePath": "en/guide/README.md",
      "key": "v-4ca31fec",
      "path": "/en/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Feature",
          "slug": "feature"
        },
        {
          "level": 2,
          "title": "Install",
          "slug": "install"
        },
        {
          "level": 2,
          "title": "Usage",
          "slug": "usage"
        },
        {
          "level": 3,
          "title": "Global import",
          "slug": "global-import"
        },
        {
          "level": 3,
          "title": "Demand import",
          "slug": "demand-import"
        },
        {
          "level": 2,
          "title": "Configure",
          "slug": "configure"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "logo.png",
    "repo": "https://github.com/MrPluto0/CreateUI",
    "repoLabel": "Github",
    "locales": {
      "/": {
        "selectText": "选择语言",
        "label": "简体中文",
        "nav": [
          {
            "text": "主页",
            "link": "/"
          },
          {
            "text": "指南",
            "link": "/guide/"
          },
          {
            "text": "组件",
            "link": "/components/"
          }
        ],
        "sidebar": {
          "/components/": [
            [
              "",
              "介绍"
            ],
            {
              "title": "畅聊气泡",
              "path": "chatbox"
            },
            {
              "title": "加载动画",
              "path": "loading"
            },
            {
              "title": "消息提示框",
              "path": "toast"
            },
            {
              "title": "模态对话框",
              "path": "modal"
            },
            {
              "title": "八音盒",
              "path": "musicbox"
            }
          ]
        }
      },
      "/en/": {
        "selectText": "Languages",
        "label": "English",
        "nav": [
          {
            "text": "Home",
            "link": "/"
          },
          {
            "text": "Guide",
            "link": "/en/guide/"
          },
          {
            "text": "Components",
            "link": "/en/components/"
          }
        ],
        "sidebar": {
          "/en/components/": [
            [
              "",
              "Intro"
            ],
            {
              "title": "Chatting Bubble",
              "path": "chatbox"
            },
            {
              "title": "Loading Anime",
              "path": "loading"
            },
            {
              "title": "Message Box",
              "path": "toast"
            },
            {
              "title": "Dialog Box",
              "path": "modal"
            },
            {
              "title": "Music Box",
              "path": "musicbox"
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "description": "一个专属个性组件库",
      "path": "/"
    },
    "/en/": {
      "lang": "en-US",
      "description": "A personalized components lib.",
      "path": "/en/"
    }
  }
}